### Print directive, Data Types and Math Ops

**Data Types**
- Number (int): `1`, `2`, `300`, `0`, `-5`
- Number (float): `1.5`, `0.66`, `3.1416`
- String (str): `"Anant Mittal",` `"anantm@vehant.com"`, `""`, `"    "`
- Boolean (bool): `True`, `False`

**Check the data type** <br>

Use `type()` for finding the type of any data. Use `isinstance()` to check if the data is of particular data type.

In [58]:
print(True+1.0)
print(4//3)
print(3//2)
print(-3//2)
print("Vehant"+"technologies")
print("vehant"*3)
print("-"*30)
print(5**2)
print(5%2)
print(type(1))
print(isinstance(1,int))

2.0
1
1
-2
Vehanttechnologies
vehantvehantvehant
------------------------------
25
1
<class 'int'>
True


### Python Variables

In [51]:
x = 4
x = 5.6
x = "Annat"

### Condtionals (If-elif-else)

In [ ]:
a, b, c = 2, 4, 5

# check if the triangle is valid or not
if (a+b>c) and (b+c>a) and (a+c>b):
    print("Valid")
else:
    print("Invalid")
    
# check if the triangle is equilateral, isoceles or scalene
# can use (a==b==c) --> chained operation
if a==b==c: 
    print("Equilateral")
elif a!=b and b!=c and c!=a:
    print("Scalene")
else:
    print("Isosceles")

### Loops (for, while)

`range()` has two signatures, 
- `range(stop)` 
- `range(start, stop, step=1)`

The stop value is the value before which the sequence needs to end, so `range(3, 6)` will give `[3, 4, 5]`

In [77]:
list(range(20))
list(range(3, 6))

for i in range(5):
    print(i, i+1, sep=",", end="\n")

i=0
while i < 10:
    print(i)
    i += 1

0,1
1,2
2,3
3,4
4,5
0
1
2
3
4
5
6
7
8
9


### User-input

In [71]:
var = float(input("Enter something"))

Enter something2.1


In [72]:
print(var+1)

3.1


### Lists

In [84]:
marks = [100, 95, 33, 44, '89']
print(marks)

marks[1:3] = [1, 2, 3, 4, 5]
print(marks)

[100, 95, 33, 44, '89']
[100, 1, 2, 3, 4, 5, 44, '89']


### Functions

### Memory and pointers

In [102]:
# a = [10, 20, 30]
# print(a)
# b = a
# print(b)

# a[1] = 40
# print(a)
# print(b)

# print(id(a), id(b))

# a_ = 10
# print(id(a_))
# b_ = a_
# print(id(a_), id(b_))
# a_ = 6
# print(id(a_), id(b_))

a = [10, 20, 30]
d = list(a)
print(a)
print(d)
print(id(a), id(d))
e = a[:]
print(id(e))
print(a == d)
print(a is d)

[10, 20, 30]
[10, 20, 30]
4752281800 4596825992
4751674632
True
False


### Object Oriented Programming

In [117]:
# class Student:
#     pass

# s1 = Student()
# s2 = Student()
# s3 = Student()
# print(s1)
# print(s2)
# print(s3)
# print(Student)

# s1.name = "Anant"
# s1.rollNumber = 1
# s2.name = "Billy"
# s2.rollNumber = 2
# print(s1.name, s1.rollNumber)
# print(s2.name, s2.rollNumber)

# class Student:
#     name = None
#     rollNumber = None

class Student:
    def __init__(self, name, roll_number):
        print("Creating an object")
        self.name = name
        self.roll_number = roll_number

    def __str__(self):
        return f"Student's name is {self.name}, and roll number is {self.roll_number}"

s1 = Student("Anne", 1)
print(s1.roll_number)
s2 = Student("Billy", 2)
s2.works_for = "Something" # creating some specific attribute
#print(s1.works_for)
print(s2.works_for)

Creating an object
1
Creating an object
Something


In [123]:
class Account:
    counter = 0
    
    def __init__(self, balance=0):
        Account.counter += 1
        self.account_no = Account.counter
        self.__balance = balance # Name Mangling
        self.trans = 0
        self.max_trans = 3
    
    def deposit(self, amount):
        if amount > 0 and self.trans < self.max_trans:
            self.__balance += amount
            self.trans += 1
        else:
            return False
        return True
    
    def withdraw(self, amount):
        if self.__balance >= amount  and self.trans < self.max_trans:
            self.__balance -= amount
            self.trans += 1
        return amount
    
    def add_interest(self, interest_amount):
        self.__balance += interest_amount
        
    def __str__(self):
        return f"Account Number: {self.account_no}\n" \
               f"Balance: {self.__balance}"
    
    def get_balance(self):
        return self.__balance

a1 = Account()
print(a1)
a1.deposit(100)
print(a1)
a1.withdraw(50)
print(a1)
a1.withdraw(20)
print(a1)
#print(a1.__balance)
a1.__balance = 9999
print(a1.__balance)
print(a1.get_balance())

class SavingsAccount(Account):
    def get_interest(self):
        return 0.03 * self.get_balance()
    
    def add_interest(self):
        interest = self.get_interest()
        super().add_interest(interest)

class CurrentAccount(Account):
    def __init__(self, bal=0):
        super().__init__(bal)
        self.max_trans = 10

s1 = CurrentAccount(10)
print(s1.max_trans)

Account Number: 1
Balance: 0
Account Number: 1
Balance: 100
Account Number: 1
Balance: 50
Account Number: 1
Balance: 30
9999
30
10


### Numpy

In [128]:
import numpy as np
a = [1, 2, 3, 4]
print(a * 2)

b = np.array([1, 2, 3, 4]) # we call them array instead of lists
print(b * 2) # vectorization or broadcasting

# implicit type conversion
a = np.array([1, 100, 0, 101.2, "anant"])
print(a)


# explicit type conversion
a = np.array([-1, 0, 1, 129], dtype="int16")
print(a)
b = a.astype("float")
print(b)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]
['1' '100' '0' '101.2' 'anant']
[ -1   0   1 129]
[ -1.   0.   1. 129.]


#### Reshape the array

In [130]:
a = np.arange(1, 13)
a = a.reshape(3, 4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### Indexing and Splicing

In [138]:
a = np.arange(12)
# print(a[2:7])
# print(a[:7])
# print(a[::2])

b = a.reshape(3, 4) # 2-D conversion
# print(b[0, 1])
# print(b[0])
print(b[0, 1:])
c = b[:, ::2]
print(c.shape)
print(a.flags)
print(b.flags['OWNDATA'])

[1 2 3]
(3, 2)
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

False


#### Vectoriztion or Broadcating

In [141]:
a = np.arange(1, 6)
print(a)
#print(a*2)
print(a < 3)

[1 2 3 4 5]
[ True  True False False False]


#### Re-visiting shape and re-shape

In [147]:
a = np.arange(12)
b = a.reshape(1, 12)
print(a.shape)
#print(b.shape)
# print(b.shape)
print(b.T.shape)
print(a.reshape(2,-1)) #  can only specify one unknown dimension

(12,)
(12, 1)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


#### Masking

Masking generates a new copy of the array

In [155]:
a_np = np.arange(30)
a = list(range(30))
mask = list(a_np > 15)
#print(mask)
print(a_np[mask])
print(a_np[a_np>15]) # this can't be done on Python lists
#print(a[[1, 2, 4]])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29]


#### Checking the Numpy array flags

In [156]:
a_np.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

#### Some special arrays

In [159]:
x = 12
print(np.empty(7)) # what garbage value that is present there
print(np.ones((3, 4))* x) # creates an array of 5 elements with value x
print(np.zeros((3, 4))) # provide dimension in tuple for multi-dimensional array

[ 2.0000000e+000 -1.4945711e-154  1.9762626e-323  0.0000000e+000
  0.0000000e+000  0.0000000e+000  2.0000000e+000]
[[12. 12. 12. 12.]
 [12. 12. 12. 12.]
 [12. 12. 12. 12.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### Axis 

In [163]:
a = np.arange(12)
print(a.sum())
b = a.reshape(3, 4)
print(b.sum())

print(b)
print(b.sum(axis=0))

66
66
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]


#### Reproducibility (seed function)

In [168]:
from time import time
print(time()) # Jan 1, 1970

1582021210.697855


In [172]:
import random
print(random.random())
print(random.random())
print(random.random())

0.4683793802760553
0.3515409767270241
0.22737254003902674


In [177]:
random.seed(112)
print(random.random())
print(random.random())
print(random.random())

0.48124663407330837
0.6660875572249376
0.6198336951349463
